import type { ClassificationResult } from '../types'

export type ClassificationKey = ClassificationResult['classification']

export interface ClassificationConfigEntry {
    label: string
    labelLong: string
    description: string
    clinicalInterpretation: string
    className: string
    color: string
    bgColor: string
    hexColor: string
    borderColor: string
    segmentBg: string
    segmentBorder: string
    segmentChip: string
    suggestedActions: string[]
}

// ── Classification Config (single source of truth) ───────────────────────────
export const CLASSIFICATION_CONFIG: Record<ClassificationKey, ClassificationConfigEntry> = {
    normal: {
        label: 'Normal',
        labelLong: 'Normal Breath Sounds',
        description:
            'No adventitious sounds detected. Clear bilateral breath sounds with normal vesicular pattern.',
        clinicalInterpretation:
            'Auscultation reveals vesicular breath sounds bilaterally without adventitious sounds. No crackles, wheezes, or rhonchi identified.',
        className: 'badge-normal',
        color: 'text-[#047857]',
        bgColor: 'bg-[#D1FAE5]',
        hexColor: '#047857',
        borderColor: 'border-l-[#047857]',
        segmentBg: 'rgba(4, 120, 87, 0.15)',
        segmentBorder: 'rgba(4, 120, 87, 0.4)',
        segmentChip: 'bg-[#D1FAE5] text-[#047857]',
        suggestedActions: [
            'No immediate follow-up required based on auscultation findings',
            'Continue routine monitoring if clinically indicated',
            'Document normal baseline for future comparison',
        ],
    },
    crackles: {
        label: 'Crackles',
        labelLong: 'Crackles Detected',
        description:
            'Fine or coarse crackles identified. Non-continuous, brief, explosive sounds typically heard during inspiration, suggestive of parenchymal disease.',
        clinicalInterpretation:
            'Adventitious crackles detected during auscultation. These non-continuous, explosive sounds may indicate fluid or secretions in the airways, interstitial lung disease, or early pneumonia.',
        className: 'badge-crackles',
        color: 'text-[#B45309]',
        bgColor: 'bg-[#FEF3C7]',
        hexColor: '#B45309',
        borderColor: 'border-l-[#B45309]',
        segmentBg: 'rgba(180, 83, 9, 0.15)',
        segmentBorder: 'rgba(180, 83, 9, 0.4)',
        segmentChip: 'bg-[#FEF3C7] text-[#B45309]',
        suggestedActions: [
            'Correlate with chest radiograph if not recently obtained',
            'Assess oxygen saturation and respiratory rate',
            'Consider pulmonary function testing if chronic',
            'Evaluate for signs of heart failure (peripheral edema, JVD)',
        ],
    },
    wheezes: {
        label: 'Wheezes',
        labelLong: 'Wheezes Detected',
        description:
            'Continuous musical sounds identified. Typically high-pitched, generated by airflow through narrowed airways, indicative of obstructive pathology.',
        clinicalInterpretation:
            'Wheezing detected on auscultation. These continuous, musical sounds indicate airflow limitation through narrowed or compressed airways, consistent with bronchospasm or obstructive airway disease.',
        className: 'badge-wheezes',
        color: 'text-[#C2410C]',
        bgColor: 'bg-[#FFEDD5]',
        hexColor: '#C2410C',
        borderColor: 'border-l-[#C2410C]',
        segmentBg: 'rgba(194, 65, 12, 0.15)',
        segmentBorder: 'rgba(194, 65, 12, 0.4)',
        segmentChip: 'bg-[#FFEDD5] text-[#C2410C]',
        suggestedActions: [
            'Assess bronchodilator responsiveness if not previously documented',
            'Consider spirometry for obstructive pattern quantification',
            'Evaluate medication compliance (inhaler technique, controller therapy)',
            'Monitor peak expiratory flow if asthma suspected',
        ],
    },
    both: {
        label: 'Crackles & Wheezes',
        labelLong: 'Crackles & Wheezes',
        description:
            'Both crackles and wheezes detected. Mixed adventitious sounds suggest complex or advanced respiratory pathology requiring further evaluation.',
        clinicalInterpretation:
            'Mixed adventitious sounds detected: both crackles and wheezes present on auscultation. This combination may indicate advanced COPD with exacerbation, bronchiectasis, or complex respiratory pathology with both obstructive and parenchymal components.',
        className: 'badge-both',
        color: 'text-[#B91C1C]',
        bgColor: 'bg-[#FEE2E2]',
        hexColor: '#B91C1C',
        borderColor: 'border-l-[#B91C1C]',
        segmentBg: 'rgba(185, 28, 28, 0.15)',
        segmentBorder: 'rgba(185, 28, 28, 0.4)',
        segmentChip: 'bg-[#FEE2E2] text-[#B91C1C]',
        suggestedActions: [
            'Urgent: chest imaging (CXR or CT) recommended',
            'Obtain complete blood count and inflammatory markers',
            'Consider pulmonology referral for complex presentation',
            'Assess need for supplemental oxygen',
            'Evaluate for acute exacerbation triggers (infection, environmental)',
        ],
    },
}

// ── Disease clinical notes (keyed by disease name) ──────────────────────────
export const DISEASE_CLINICAL_NOTES: Record<string, string> = {
    COPD: 'Consistent with obstructive airway pattern; correlate with spirometry (FEV1/FVC ratio)',
    Healthy: 'No significant pathology suggested by acoustic analysis',
    URTI: 'Upper airway involvement; typically self-limiting but monitor for lower tract progression',
    Pneumonia: 'Parenchymal consolidation pattern; consider chest imaging and inflammatory markers',
    Bronchiectasis: 'Suggests chronic airway dilation with secretion retention; consider HRCT for confirmation',
    Bronchiolitis: 'Small airway involvement; common in pediatric patients; assess hydration and oxygen status',
    Asthma: 'Reversible obstructive pattern; assess bronchodilator response and trigger avoidance',
    LRTI: 'Lower respiratory tract involvement; evaluate severity with imaging and inflammatory markers',
}

/** Hex colors for charts and inline styles */
export const CLASSIFICATION_HEX: Record<ClassificationKey, string> = {
    normal: '#047857',
    crackles: '#B45309',
    wheezes: '#C2410C',
    both: '#B91C1C',
}

// ── Severity Config ─────────────────────────────────────────────────────────
export const SEVERITY_CONFIG = {
    thresholds: [25, 50, 75] as const,
    low: { className: 'severity-low', hex: '#047857' },
    moderate: { className: 'severity-moderate', hex: '#B45309' },
    high: { className: 'severity-high', hex: '#C2410C' },
    critical: { className: 'severity-critical', hex: '#B91C1C' },
} as const

export function getSeverityClass(severity: number): string {
    if (severity < 25) return SEVERITY_CONFIG.low.className
    if (severity < 50) return SEVERITY_CONFIG.moderate.className
    if (severity < 75) return SEVERITY_CONFIG.high.className
    return SEVERITY_CONFIG.critical.className
}

export function getSeverityColor(severity: number): string {
    if (severity < 25) return SEVERITY_CONFIG.low.hex
    if (severity < 50) return SEVERITY_CONFIG.moderate.hex
    if (severity < 75) return SEVERITY_CONFIG.high.hex
    return SEVERITY_CONFIG.critical.hex
}

export function getSeverityLabel(severity: number): string {
    if (severity < 25) return 'Low'
    if (severity < 50) return 'Moderate'
    if (severity < 75) return 'High'
    return 'Critical'
}

export function getSeverityClinicalGuidance(severity: number): string {
    if (severity < 25) return 'Findings suggest minimal respiratory compromise. Routine follow-up appropriate.'
    if (severity < 50)
        return 'Moderate abnormality detected. Clinical correlation recommended; consider follow-up auscultation.'
    if (severity < 75)
        return 'Significant respiratory abnormality. Further diagnostic workup and closer monitoring advised.'
    return 'Severe abnormality. Urgent evaluation recommended. Consider imaging and specialist referral.'
}

export function getConfidenceLevel(confidence: number): { label: string; guidance: string } {
    if (confidence >= 0.85)
        return { label: 'High confidence', guidance: 'Classification is well-supported by acoustic features.' }
    if (confidence >= 0.65)
        return {
            label: 'Moderate confidence',
            guidance: 'Consider re-auscultation or additional clinical correlation.',
        }
    return {
        label: 'Low confidence',
        guidance: 'Acoustic signal quality may be suboptimal. Re-recording recommended for reliable classification.',
    }
}

// ── Format Helpers ──────────────────────────────────────────────────────────
export type DateFormat = 'short' | 'medium' | 'long'

export function formatDate(iso: string, format: DateFormat = 'medium'): string {
    const opts: Intl.DateTimeFormatOptions =
        format === 'short'
            ? { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' }
            : format === 'medium'
              ? {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                }
              : {
                    weekday: 'long',
                    year: 'numeric',
                    month: 'long',
                    day: 'numeric',
                    hour: '2-digit',
                    minute: '2-digit',
                }
    return new Date(iso).toLocaleDateString('en-US', opts)
}
